services:
  app:
    build: .
    container_name: merger-frontend
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Dubai
    volumes:
      - ./dist:/usr/share/nginx/html
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped